//Auth
export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";


//USERS

export const FETCH_USERS_REQUESTED = "FETCH_USERS_REQUESTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const CHANGE_USER = "CHANGE_USER";

export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const NEW_USER = "NEW_USER";
export const SAVE_USER_REQUESTED = "SAVE_USER_REQUESTED";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAILED = "SAVE_USER_FAILED";

export const UPDATE_USER_REQUESTED = "UPDATE_USER_REQUESTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUESTED = "DELETE_USER_REQUESTED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//ROLES

export const FETCH_ROLES_REQUESTED = "FETCH_ROLES_REQUESTED";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILED = "FETCH_ROLES_FAILED";

export const CHANGE_ROLE = "CHANGE_ROLE";

export const FETCH_ROLE_REQUESTED = "FETCH_ROLE_REQUESTED";
export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAILED = "FETCH_ROLE_FAILED";

export const NEW_ROLE = "NEW_ROLE";
export const SAVE_ROLE_REQUESTED = "SAVE_ROLE_REQUESTED";
export const SAVE_ROLE_SUCCESS = "SAVE_ROLE_SUCCESS";
export const SAVE_ROLE_FAILED = "SAVE_ROLE_FAILED";

export const UPDATE_ROLE_REQUESTED = "UPDATE_ROLE_REQUESTED";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILED = "UPDATE_ROLE_FAILED";

export const DELETE_ROLE_REQUESTED = "DELETE_ROLE_REQUESTED";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";

//CUSTOMERS

export const FETCH_CUSTOMERS_REQUESTED = "FETCH_CUSTOMERS_REQUESTED";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAILED = "FETCH_CUSTOMERS_FAILED";

export const CHANGE_CUSTOMER = "CHANGE_CUSTOMER";

export const FETCH_CUSTOMER_REQUESTED = "FETCH_CUSTOMER_REQUESTED";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAILED = "FETCH_CUSTOMER_FAILED";

export const NEW_CUSTOMER = "NEW_CUSTOMER";
export const SAVE_CUSTOMER_REQUESTED = "SAVE_CUSTOMER_REQUESTED";
export const SAVE_CUSTOMER_SUCCESS = "SAVE_CUSTOMER_SUCCESS";
export const SAVE_CUSTOMER_FAILED = "SAVE_CUSTOMER_FAILED";

export const UPDATE_CUSTOMER_REQUESTED = "UPDATE_CUSTOMER_REQUESTED";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILED = "UPDATE_CUSTOMER_FAILED";

export const DELETE_CUSTOMER_REQUESTED = "DELETE_CUSTOMER_REQUESTED";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILED = "DELETE_CUSTOMER_FAILED";

//SUPPLIERS

export const FETCH_SUPPLIERS_REQUESTED = "FETCH_SUPPLIERS_REQUESTED";
export const FETCH_SUPPLIERS_SUCCESS = "FETCH_SUPPLIERS_SUCCESS";
export const FETCH_SUPPLIERS_FAILED = "FETCH_SUPPLIERS_FAILED";

export const CHANGE_SUPPLIER = "CHANGE_SUPPLIER";

export const FETCH_SUPPLIER_REQUESTED = "FETCH_SUPPLIER_REQUESTED";
export const FETCH_SUPPLIER_SUCCESS = "FETCH_SUPPLIER_SUCCESS";
export const FETCH_SUPPLIER_FAILED = "FETCH_SUPPLIER_FAILED";

export const NEW_SUPPLIER = "NEW_SUPPLIER";
export const SAVE_SUPPLIER_REQUESTED = "SAVE_SUPPLIER_REQUESTED";
export const SAVE_SUPPLIER_SUCCESS = "SAVE_SUPPLIER_SUCCESS";
export const SAVE_SUPPLIER_FAILED = "SAVE_SUPPLIER_FAILED";

export const UPDATE_SUPPLIER_REQUESTED = "UPDATE_SUPPLIER_REQUESTED";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_FAILED = "UPDATE_SUPPLIER_FAILED";

export const DELETE_SUPPLIER_REQUESTED = "DELETE_SUPPLIER_REQUESTED";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_FAILED = "DELETE_SUPPLIER_FAILED";

//PAYMENTS

export const FETCH_PAYMENTS_REQUESTED = "FETCH_PAYMENTS_REQUESTED";
export const FETCH_PAYMENTS_SUCCESS = "FETCH_PAYMENTS_SUCCESS";
export const FETCH_PAYMENTS_FAILED = "FETCH_PAYMENTS_FAILED";

export const CHANGE_PAYMENT = "CHANGE_PAYMENT";

export const FETCH_PAYMENT_REQUESTED = "FETCH_PAYMENT_REQUESTED";
export const FETCH_PAYMENT_SUCCESS = "FETCH_PAYMENT_SUCCESS";
export const FETCH_PAYMENT_FAILED = "FETCH_PAYMENT_FAILED";

export const NEW_PAYMENT = "NEW_PAYMENT";
export const SAVE_PAYMENT_REQUESTED = "SAVE_PAYMENT_REQUESTED";
export const SAVE_PAYMENT_SUCCESS = "SAVE_PAYMENT_SUCCESS";
export const SAVE_PAYMENT_FAILED = "SAVE_PAYMENT_FAILED";

export const UPDATE_PAYMENT_REQUESTED = "UPDATE_PAYMENT_REQUESTED";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILED = "UPDATE_PAYMENT_FAILED";

export const DELETE_PAYMENT_REQUESTED = "DELETE_PAYMENT_REQUESTED";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAILED = "DELETE_SUPPLIER_FAILED";

//MODAL

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";