//Auth
export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//USERS

export const FETCH_USERS_REQUESTED = "FETCH_USERS_REQUESTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const CHANGE_USER = "CHANGE_USER";

export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const NEW_USER = "NEW_USER";
export const SAVE_USER_REQUESTED = "SAVE_USER_REQUESTED";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAILED = "SAVE_USER_FAILED";

export const UPDATE_USER_REQUESTED = "UPDATE_USER_REQUESTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUESTED = "DELETE_USER_REQUESTED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//ROLES

export const FETCH_ROLES_REQUESTED = "FETCH_ROLES_REQUESTED";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILED = "FETCH_ROLES_FAILED";

export const CHANGE_ROLE = "CHANGE_ROLE";

export const FETCH_ROLE_REQUESTED = "FETCH_ROLE_REQUESTED";
export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAILED = "FETCH_ROLE_FAILED";

export const NEW_ROLE = "NEW_ROLE";
export const SAVE_ROLE_REQUESTED = "SAVE_ROLE_REQUESTED";
export const SAVE_ROLE_SUCCESS = "SAVE_ROLE_SUCCESS";
export const SAVE_ROLE_FAILED = "SAVE_ROLE_FAILED";

export const UPDATE_ROLE_REQUESTED = "UPDATE_ROLE_REQUESTED";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILED = "UPDATE_ROLE_FAILED";

export const DELETE_ROLE_REQUESTED = "DELETE_ROLE_REQUESTED";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";

//PETS

export const FETCH_PETS_REQUESTED = "FETCH_PETS_REQUESTED";
export const FETCH_PETS_SUCCESS = "FETCH_PETS_SUCCESS";
export const FETCH_PETS_FAILED = "FETCH_PETS_FAILED";

export const CHANGE_PET = "CHANGE_PET";

export const FETCH_PET_REQUESTED = "FETCH_PET_REQUESTED";
export const FETCH_PET_SUCCESS = "FETCH_PET_SUCCESS";
export const FETCH_PET_FAILED = "FETCH_PET_FAILED";

export const NEW_PET = "NEW_PET";
export const SAVE_PET_REQUESTED = "SAVE_PET_REQUESTED";
export const SAVE_PET_SUCCESS = "SAVE_PET_SUCCESS";
export const SAVE_PET_FAILED = "SAVE_PET_FAILED";

export const UPDATE_PET_REQUESTED = "UPDATE_PET_REQUESTED";
export const UPDATE_PET_SUCCESS = "UPDATE_PET_SUCCESS";
export const UPDATE_PET_FAILED = "UPDATE_PET_FAILED";

export const DELETE_PET_REQUESTED = "DELETE_PET_REQUESTED";
export const DELETE_PET_SUCCESS = "DELETE_PET_SUCCESS";
export const DELETE_PET_FAILED = "DELETE_PET_FAILED";

//PRODUCTS

export const FETCH_PRODUCTS_REQUESTED = "FETCH_PRODUCTS_REQUESTED";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const CHANGE_PRODUCT = "CHANGE_PRODUCT";

export const FETCH_PRODUCT_REQUESTED = "FETCH_PRODUCT_REQUESTED";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";

export const NEW_PRODUCT = "NEW_PRODUCT";
export const SAVE_PRODUCT_REQUESTED = "SAVE_PRODUCT_REQUESTED";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAILED = "SAVE_PRODUCT_FAILED";

export const UPDATE_PRODUCT_REQUESTED = "UPDATE_PRODUCT_REQUESTED";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUESTED = "DELETE_PRODUCT_REQUESTED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

//PRODUCTCATEGORIES

export const FETCH_PRODUCTCATEGORIES_REQUESTED = "FETCH_PRODUCTCATEGORIES_REQUESTED";
export const FETCH_PRODUCTCATEGORIES_SUCCESS = "FETCH_PRODUCTCATEGORIES_SUCCESS";
export const FETCH_PRODUCTCATEGORIES_FAILED = "FETCH_PRODUCTCATEGORIES_FAILED";

export const CHANGE_PRODUCTCATEGORY = "CHANGE_PRODUCTCATEGORY";

export const FETCH_PRODUCTCATEGORY_REQUESTED = "FETCH_PRODUCTCATEGORY_REQUESTED";
export const FETCH_PRODUCTCATEGORY_SUCCESS = "FETCH_PRODUCTCATEGORY_SUCCESS";
export const FETCH_PRODUCTCATEGORY_FAILED = "FETCH_PRODUCTCATEGORY_FAILED";

export const NEW_PRODUCTCATEGORY = "NEW_PRODUCTCATEGORY";
export const SAVE_PRODUCTCATEGORY_REQUESTED = "SAVE_PRODUCTCATEGORY_REQUESTED";
export const SAVE_PRODUCTCATEGORY_SUCCESS = "SAVE_PRODUCTCATEGORY_SUCCESS";
export const SAVE_PRODUCTCATEGORY_FAILED = "SAVE_PRODUCTCATEGORY_FAILED";

export const UPDATE_PRODUCTCATEGORY_REQUESTED = "UPDATE_PRODUCTCATEGORY_REQUESTED";
export const UPDATE_PRODUCTCATEGORY_SUCCESS = "UPDATE_PRODUCTCATEGORY_SUCCESS";
export const UPDATE_PRODUCTCATEGORY_FAILED = "UPDATE_PRODUCTCATEGORY_FAILED";

export const DELETE_PRODUCTCATEGORY_REQUESTED = "DELETE_PRODUCTCATEGORY_REQUESTED";
export const DELETE_PRODUCTCATEGORY_SUCCESS = "DELETE_PRODUCTCATEGORY_SUCCESS";
export const DELETE_PRODUCTCATEGORY_FAILED = "DELETE_PRODUCTCATEGORY_FAILED";

//CURRENCYUNITS

export const FETCH_CURRENCYUNITS_REQUESTED = "FETCH_CURRENCYUNITS_REQUESTED";
export const FETCH_CURRENCYUNITS_SUCCESS = "FETCH_CURRENCYUNITS_SUCCESS";
export const FETCH_CURRENCYUNITS_FAILED = "FETCH_CURRENCYUNITS_FAILED";

export const CHANGE_CURRENCYUNIT = "CHANGE_CURRENCYUNIT";

export const FETCH_CURRENCYUNIT_REQUESTED = "FETCH_CURRENCYUNIT_REQUESTED";
export const FETCH_CURRENCYUNIT_SUCCESS = "FETCH_CURRENCYUNIT_SUCCESS";
export const FETCH_CURRENCYUNIT_FAILED = "FETCH_CURRENCYUNIT_FAILED";

export const NEW_CURRENCYUNIT = "NEW_CURRENCYUNIT";
export const SAVE_CURRENCYUNIT_REQUESTED = "SAVE_CURRENCYUNIT_REQUESTED";
export const SAVE_CURRENCYUNIT_SUCCESS = "SAVE_CURRENCYUNIT_SUCCESS";
export const SAVE_CURRENCYUNIT_FAILED = "SAVE_CURRENCYUNIT_FAILED";

export const UPDATE_CURRENCYUNIT_REQUESTED = "UPDATE_CURRENCYUNIT_REQUESTED";
export const UPDATE_CURRENCYUNIT_SUCCESS = "UPDATE_CURRENCYUNIT_SUCCESS";
export const UPDATE_CURRENCYUNIT_FAILED = "UPDATE_CURRENCYUNIT_FAILED";

export const DELETE_CURRENCYUNIT_REQUESTED = "DELETE_CURRENCYUNIT_REQUESTED";
export const DELETE_CURRENCYUNIT_SUCCESS = "DELETE_CURRENCYUNIT_SUCCESS";
export const DELETE_CURRENCYUNIT_FAILED = "DELETE_CURRENCYUNIT_FAILED";

//MEASUREMENTUNITS

export const FETCH_MEASUREMENTUNITS_REQUESTED = "FETCH_MEASUREMENTUNITS_REQUESTED";
export const FETCH_MEASUREMENTUNITS_SUCCESS = "FETCH_MEASUREMENTUNITS_SUCCESS";
export const FETCH_MEASUREMENTUNITS_FAILED = "FETCH_MEASUREMENTUNITS_FAILED";

export const CHANGE_MEASUREMENTUNIT = "CHANGE_MEASUREMENTUNIT";

export const FETCH_MEASUREMENTUNIT_REQUESTED = "FETCH_MEASUREMENTUNIT_REQUESTED";
export const FETCH_MEASUREMENTUNIT_SUCCESS = "FETCH_MEASUREMENTUNIT_SUCCESS";
export const FETCH_MEASUREMENTUNIT_FAILED = "FETCH_MEASUREMENTUNIT_FAILED";

export const NEW_MEASUREMENTUNIT = "NEW_MEASUREMENTUNIT";
export const SAVE_MEASUREMENTUNIT_REQUESTED = "SAVE_MEASUREMENTUNIT_REQUESTED";
export const SAVE_MEASUREMENTUNIT_SUCCESS = "SAVE_MEASUREMENTUNIT_SUCCESS";
export const SAVE_MEASUREMENTUNIT_FAILED = "SAVE_MEASUREMENTUNIT_FAILED";

export const UPDATE_MEASUREMENTUNIT_REQUESTED = "UPDATE_MEASUREMENTUNIT_REQUESTED";
export const UPDATE_MEASUREMENTUNIT_SUCCESS = "UPDATE_MEASUREMENTUNIT_SUCCESS";
export const UPDATE_MEASUREMENTUNIT_FAILED = "UPDATE_MEASUREMENTUNIT_FAILED";

export const DELETE_MEASUREMENTUNIT_REQUESTED = "DELETE_MEASUREMENTUNIT_REQUESTED";
export const DELETE_MEASUREMENTUNIT_SUCCESS = "DELETE_MEASUREMENTUNIT_SUCCESS";
export const DELETE_MEASUREMENTUNIT_FAILED = "DELETE_MEASUREMENTUNIT_FAILED";

//CLINICALINFORMATIONS

export const FETCH_CLINICALINFORMATIONS_REQUESTED = "FETCH_CLINICALINFORMATIONS_REQUESTED";
export const FETCH_CLINICALINFORMATIONS_SUCCESS = "FETCH_CLINICALINFORMATIONS_SUCCESS";
export const FETCH_CLINICALINFORMATIONS_FAILED = "FETCH_CLINICALINFORMATIONS_FAILED";

export const CHANGE_CLINICALINFORMATION = "CHANGE_CLINICALINFORMATION";

export const FETCH_CLINICALINFORMATION_REQUESTED = "FETCH_CLINICALINFORMATION_REQUESTED";
export const FETCH_CLINICALINFORMATION_SUCCESS = "FETCH_CLINICALINFORMATION_SUCCESS";
export const FETCH_CLINICALINFORMATION_FAILED = "FETCH_CLINICALINFORMATION_FAILED";

export const NEW_CLINICALINFORMATION = "NEW_CLINICALINFORMATION";
export const SAVE_CLINICALINFORMATION_REQUESTED = "SAVE_CLINICALINFORMATION_REQUESTED";
export const SAVE_CLINICALINFORMATION_SUCCESS = "SAVE_CLINICALINFORMATION_SUCCESS";
export const SAVE_CLINICALINFORMATION_FAILED = "SAVE_CLINICALINFORMATION_FAILED";

export const UPDATE_CLINICALINFORMATION_REQUESTED = "UPDATE_CLINICALINFORMATION_REQUESTED";
export const UPDATE_CLINICALINFORMATION_SUCCESS = "UPDATE_CLINICALINFORMATION_SUCCESS";
export const UPDATE_CLINICALINFORMATION_FAILED = "UPDATE_CLINICALINFORMATION_FAILED";

export const DELETE_CLINICALINFORMATION_REQUESTED = "DELETE_CLINICALINFORMATION_REQUESTED";
export const DELETE_CLINICALINFORMATION_SUCCESS = "DELETE_CLINICALINFORMATION_SUCCESS";
export const DELETE_CLINICALINFORMATION_FAILED = "DELETE_CLINICALINFORMATION_FAILED";
//INVOICES

export const FETCH_INVOICES_REQUESTED = "FETCH_INVOICES_REQUESTED";
export const FETCH_INVOICES_SUCCESS = "FETCH_INVOICES_SUCCESS";
export const FETCH_INVOICES_FAILED = "FETCH_INVOICES_FAILED";

export const CHANGE_INVOICE = "CHANGE_INVOICE";

export const FETCH_INVOICE_REQUESTED = "FETCH_INVOICE_REQUESTED";
export const FETCH_INVOICE_SUCCESS = "FETCH_INVOICE_SUCCESS";
export const FETCH_INVOICE_FAILED = "FETCH_INVOICE_FAILED";

export const NEW_INVOICE = "NEW_INVOICE";
export const SAVE_INVOICE_REQUESTED = "SAVE_INVOICE_REQUESTED";
export const SAVE_INVOICE_SUCCESS = "SAVE_INVOICE_SUCCESS";
export const SAVE_INVOICE_FAILED = "SAVE_INVOICE_FAILED";

export const UPDATE_INVOICE_REQUESTED = "UPDATE_INVOICE_REQUESTED";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_FAILED = "UPDATE_INVOICE_FAILED";

export const DELETE_INVOICE_REQUESTED = "DELETE_INVOICE_REQUESTED";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILED = "DELETE_INVOICE_FAILED";

//MODAL

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
