//Auth
export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";


//USERS

export const FETCH_USERS_REQUESTED = "FETCH_USERS_REQUESTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const CHANGE_USER = "CHANGE_USER";

export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const NEW_USER = "NEW_USER";
export const SAVE_USER_REQUESTED = "SAVE_USER_REQUESTED";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAILED = "SAVE_USER_FAILED";

export const UPDATE_USER_REQUESTED = "UPDATE_USER_REQUESTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUESTED = "DELETE_USER_REQUESTED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//ROLES

export const FETCH_ROLES_REQUESTED = "FETCH_ROLES_REQUESTED";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILED = "FETCH_ROLES_FAILED";

export const CHANGE_ROLE = "CHANGE_ROLE";

export const FETCH_ROLE_REQUESTED = "FETCH_ROLE_REQUESTED";
export const FETCH_ROLE_SUCCESS = "FETCH_ROLE_SUCCESS";
export const FETCH_ROLE_FAILED = "FETCH_ROLE_FAILED";

export const NEW_ROLE = "NEW_ROLE";
export const SAVE_ROLE_REQUESTED = "SAVE_ROLE_REQUESTED";
export const SAVE_ROLE_SUCCESS = "SAVE_ROLE_SUCCESS";
export const SAVE_ROLE_FAILED = "SAVE_ROLE_FAILED";

export const UPDATE_ROLE_REQUESTED = "UPDATE_ROLE_REQUESTED";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAILED = "UPDATE_ROLE_FAILED";

export const DELETE_ROLE_REQUESTED = "DELETE_ROLE_REQUESTED";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED";


//APPOİNTMENTS

export const FETCH_APPOİNTMENTS_REQUESTED = "FETCH_APPOİNTMENTS_REQUESTED";
export const FETCH_APPOİNTMENTS_SUCCESS = "FETCH_APPOİNTMENTS_SUCCESS";
export const FETCH_APPOİNTMENTS_FAILED = "FETCH_APPOİNTMENTS_FAILED";

export const CHANGE_APPOİNTMENT = "CHANGE_APPOİNTMENT";

export const FETCH_APPOİNTMENT_REQUESTED = "FETCH_APPOİNTMENT_REQUESTED";
export const FETCH_APPOİNTMENT_SUCCESS = "FETCH_APPOİNTMENT_SUCCESS";
export const FETCH_APPOİNTMENT_FAILED = "FETCH_APPOİNTMENT_FAILED";

export const NEW_APPOİNTMENT = "NEW_APPOİNTMENT";
export const SAVE_APPOİNTMENT_REQUESTED = "SAVE_APPOİNTMENT_REQUESTED";
export const SAVE_APPOİNTMENT_SUCCESS = "SAVE_APPOİNTMENT_SUCCESS";
export const SAVE_APPOİNTMENT_FAILED = "SAVE_APPOİNTMENT_FAILED";

export const UPDATE_APPOİNTMENT_REQUESTED = "UPDATE_APPOİNTMENT_REQUESTED";
export const UPDATE_APPOİNTMENT_SUCCESS = "UPDATE_APPOİNTMENT_SUCCESS";
export const UPDATE_APPOİNTMENT_FAILED = "UPDATE_APPOİNTMENT_FAILED";

export const DELETE_APPOİNTMENT_REQUESTED = "DELETE_APPOİNTMENT_REQUESTED";
export const DELETE_APPOİNTMENT_SUCCESS = "DELETE_APPOİNTMENT_SUCCESS";
export const DELETE_APPOİNTMENT_FAILED = "DELETE_APPOİNTMENT_FAILED";



//PETS

export const FETCH_PETS_REQUESTED = "FETCH_PETS_REQUESTED";
export const FETCH_PETS_SUCCESS = "FETCH_PETS_SUCCESS";
export const FETCH_PETS_FAILED = "FETCH_PETS_FAILED";

export const CHANGE_PET = "CHANGE_PET";

export const FETCH_PET_REQUESTED = "FETCH_PET_REQUESTED";
export const FETCH_PET_SUCCESS = "FETCH_PET_SUCCESS";
export const FETCH_PET_FAILED = "FETCH_PET_FAILED";

export const NEW_PET = "NEW_PET";
export const SAVE_PET_REQUESTED = "SAVE_PET_REQUESTED";
export const SAVE_PET_SUCCESS = "SAVE_PET_SUCCESS";
export const SAVE_PET_FAILED = "SAVE_PET_FAILED";

export const UPDATE_PET_REQUESTED = "UPDATE_PET_REQUESTED";
export const UPDATE_PET_SUCCESS = "UPDATE_PET_SUCCESS";
export const UPDATE_PET_FAILED = "UPDATE_PET_FAILED";

export const DELETE_PET_REQUESTED = "DELETE_PET_REQUESTED";
export const DELETE_PET_SUCCESS = "DELETE_PET_SUCCESS";
export const DELETE_PET_FAILED = "DELETE_PET_FAILED";

//PRODUCTS

export const FETCH_PRODUCTS_REQUESTED = "FETCH_PRODUCTS_REQUESTED";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const CHANGE_PRODUCT = "CHANGE_PRODUCT";

export const FETCH_PRODUCT_REQUESTED = "FETCH_PRODUCT_REQUESTED";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";

export const NEW_PRODUCT = "NEW_PRODUCT";
export const SAVE_PRODUCT_REQUESTED = "SAVE_PRODUCT_REQUESTED";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAILED = "SAVE_PRODUCT_FAILED";

export const UPDATE_PRODUCT_REQUESTED = "UPDATE_PRODUCT_REQUESTED";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUESTED = "DELETE_PRODUCT_REQUESTED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

//MODAL

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";